-- MySQL Script generated by MySQL Workbench
-- Mon Dec  3 22:12:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shopwindow
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shopwindow
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopwindow` DEFAULT CHARACTER SET utf8 ;
USE `shopwindow` ;

-- -----------------------------------------------------
-- Table `shopwindow`.`DailySales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopwindow`.`DailySales` ;

CREATE TABLE IF NOT EXISTS `shopwindow`.`DailySales` (
  `ProductID` INT NOT NULL,
  `ProductName` VARCHAR(45) NOT NULL,
  `ProductMeasure` VARCHAR(45) NOT NULL,
  `TotalQuantity` VARCHAR(45) NOT NULL,
  `TotalPrice` DOUBLE NOT NULL,
  `OrderDay` INT NOT NULL,
  `OrderMonth` INT NOT NULL,
  `OrderYear` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
