-- MySQL Script generated by MySQL Workbench
-- Mon Dec  3 22:09:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shopdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shopdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopdb` DEFAULT CHARACTER SET utf8 ;
USE `shopdb` ;

-- -----------------------------------------------------
-- Table `shopdb`.`OrderStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopdb`.`OrderStatus` ;

CREATE TABLE IF NOT EXISTS `shopdb`.`OrderStatus` (
  `OrderStatusID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`OrderStatusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopdb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `shopdb`.`Customer` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `CompanyName` VARCHAR(45) NULL,
  `ContactName` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Address` VARCHAR(100) NULL,
  `Email` VARCHAR(100) NULL,
  `PhoneNumber` VARCHAR(14) NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`ShipmentType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopdb`.`ShipmentType` ;

CREATE TABLE IF NOT EXISTS `shopdb`.`ShipmentType` (
  `ShipmentTypeID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(255) NULL,
  PRIMARY KEY (`ShipmentTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopdb`.`Orders` ;

CREATE TABLE IF NOT EXISTS `shopdb`.`Orders` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `OrderStatusID` INT NOT NULL,
  `CustomerID` INT NOT NULL,
  `TransportTypeID` INT NOT NULL,
  `CreationDate` DATETIME NULL,
  `PlannedDate` DATETIME NULL,
  `ShipmentDate` DATETIME NULL,
  PRIMARY KEY (`OrderID`),
  CONSTRAINT `fk_Orders_OrderStatus1`
    FOREIGN KEY (`OrderStatusID`)
    REFERENCES `shopdb`.`OrderStatus` (`OrderStatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Customer1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `shopdb`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_TransportType1`
    FOREIGN KEY (`TransportTypeID`)
    REFERENCES `shopdb`.`ShipmentType` (`ShipmentTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopdb`.`Product` ;

CREATE TABLE IF NOT EXISTS `shopdb`.`Product` (
  `ProductID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Measure` VARCHAR(45) NULL,
  `Price` DOUBLE NULL,
  PRIMARY KEY (`ProductID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`OrderPosition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shopdb`.`OrderPosition` ;

CREATE TABLE IF NOT EXISTS `shopdb`.`OrderPosition` (
  `OrderPositionID` INT NOT NULL AUTO_INCREMENT,
  `OrderID` INT NOT NULL,
  `ProductID` INT NOT NULL,
  `Quantity` DOUBLE NULL,
  `CurrentPrice` DOUBLE NULL,
  PRIMARY KEY (`OrderPositionID`),
  CONSTRAINT `fk_OrderPosition_Orders`
    FOREIGN KEY (`OrderID`)
    REFERENCES `shopdb`.`Orders` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderPosition_Product1`
    FOREIGN KEY (`ProductID`)
    REFERENCES `shopdb`.`Product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
